
insert into alumnos(id,nombre,apellido) values (1,'Anderson','Taipe Reyes');
insert into alumnos(id,nombre,apellido) values (2,'Alexis','Arancibia Sanches');

insert into cuestionarios(id_cuest,id_tipo_test,tiempo,esfactor) values (1,1,4,'factor V');
insert into cuestionarios(id_cuest,id_tipo_test,tiempo,esfactor) values (2,1,3,'factor E');
insert into cuestionarios(id_cuest,id_tipo_test,tiempo,esfactor) values (3,1,5,'factor R');
insert into cuestionarios(id_cuest,id_tipo_test,tiempo,esfactor) values (4,1,2,'factor N');
insert into cuestionarios(id_cuest,id_tipo_test,tiempo,esfactor) values (5,1,4,'factor F');
insert into cuestionarios(id_cuest,id_tipo_test,tiempo,esfactor) values (6,2,0,'');

insert into tests (id_test,nom_test) values (1,'PMA');
insert into tests (id_test,nom_test) values (2,'MIND');
insert into tests (id_test,nom_test) values (3,'CASM');
insert into tests (id_test,nom_test) values (4,'ESTILOS');
insert into tests (id_test,nom_test) values (5,'ICE');

insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (1,  'Corto', 'Humano', 'Mojado', 'Moderado', '', '', 1,'HÚMEDO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (2, 'Mayor', 'Ligero', 'Estrecho', 'Vigoroso', '', '',  1,'RÁPIDO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (3,  'Variable', 'Cotidiano', 'Idiferente', 'Insostenible', '', '', 1,'DIARIO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (4, 'Expansivo', 'Alegre', 'Rígido', 'Magnífico', '', '', 1,'ESPLÉNDIDO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (5, 'Nocturno', 'Circular', 'Principal', 'Usual', '', '', 1,'HABITUAL');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (6, 'Lívido', 'Muerto', 'Líquido', 'Hablador', '', '', 1,'FLUIDO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (7, 'Gandul', 'Travieso', 'Inculto', 'Útil', '', '', 1,'HOLGAZÁN');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (8,  'Ocre', 'Absurdo', 'Trastornado', 'Abandonado', '', '', 1,'DESAMPARADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (9, 'Santo', 'Tosco', 'Escaso', 'Débil', '', '',  1,'RARO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (10, 'Fastidioso', 'Continuo', 'Difamatorio', 'Satisfecho', '', '', 1,'CONTENTO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (11,  'Risueño', 'Pobre', 'Enfadado', 'Doméstico', '', '', 1,'ENOJADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (12, 'Artificial', 'Domesticable', 'Útil', 'Picante', '', '',  1,'BENEFICIOSO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (13,  'Tónico', 'Herrumbroso', 'Informe', 'Mudo', '', '', 1,'MOHOSO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (14, 'Áspero', 'Diminuto', 'Cinestético', 'Fangoso', '', '', 1,'TOSCO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (15, 'Diagramático', 'Amorfo', 'Curativo', 'Gramatical', '', '', 1,'TERAPÉUTICO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (16, 'Sucio', 'Sombrío', 'Parco', 'Apropiado', '', '', 1,'SOBRIO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (17, 'Delicioso', 'Divertido', 'Potente', 'Forastero', '', '', 1,'FESTIVO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (18,  'Majestuoso', 'Delgado', 'Digestible', 'Válido', '', '', 1,'AUGUSTO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (19, 'Deshonroso', 'Forense', 'Hortícola', 'Impresionable', '', '',  1,'DIFAMANTE');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (20,  'Rico', 'Ciudadano', 'Cortés', 'Ignorante', '', '', 1,'EDUCADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (21,  'Oral', 'Abandonado', 'Primero', 'Fidedigno', '', '', 1,'ORIGINAL');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (22, 'Costoso', 'Nuevo', 'Hosco', 'Radical', '', '',  1,'NOVEL');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (23,  'Célebre', 'Leal', 'Renovado', 'Ágil', '', '', 1,'FAMOSO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (24, 'Laudatorio', 'Ordenado', 'Jubiloso', 'Ambicioso', '', '', 1,'SISTEMÁTICO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (25, 'Dócil', 'Grave', 'Cansado', 'Fanático', '', '', 1,'FATIGADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (26, 'Fonético', 'Acerbo', 'Brillante', 'Intrépido', '', '', 1,'RESPLANDECIENTE');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (27, 'Olvidadizo', 'Ardiente', 'Liberal', 'Provocativo', '', '', 1,'GENEROSO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (28,  'Blando', 'Facial', 'Reciente', 'Real', '', '', 1,'REGIO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (29, 'Lastimoso', 'Formal', 'Plegable', 'Pacífico', '', '',  1,'FLEXIBLE');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (30,  'Exótico', 'Aparente', 'Astuto', 'Dócil', '', '', 1,'SAGAZ');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (31,  'Paciente', 'Preferible', 'Paralelo', 'Atolondrado', '', '', 1,'IRREFLEXIVO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (32, 'Constante', 'Triste', 'Falto', 'Peculiar', '', '',  1,'DEFICIENTE');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (33,  'Alerta', 'Indulgente', 'Valeroso', 'Naciente', '', '', 1,'VIGILANTE');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (34, 'Húmedo', 'Restringido', 'Tranquilo', 'Íntimo', '', '', 1,'MINIMO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (35, 'Caballeroso', 'Autentico', 'Alevoso', 'Provable', '', '', 1,'GALANTE');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (36, 'Femenino', 'Casual', 'Aturdido', 'Cómico', '', '', 1,'ALOCADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (37, 'Cáustico', 'Fragante', 'Honorable', 'Prudente', '', '', 1,'DISCRETO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (38,  'Simplificado', 'Fatal', 'Directivo', 'Afortunado', '', '', 1,'PREDESTINADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (39, 'Importante', 'Benigno', 'Inestimable', 'Perpetuo', '', '',  1,'ETERNO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (40,  'Compuesto', 'Licencioso', 'Digno', 'Despilfarrador', '', '', 1,'PRÓDIGO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (41,  'Oculto', 'Mítico', 'Imperfecto', 'Externo', '', '', 1,'DEFECTUOSO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (42, 'Inválido', 'Oscuro', 'Indecente', 'Vermiforme', '', '',  1,'VAGO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (43,  'Clásico', 'Indispensable', 'Deplorable', 'Veraz', '', '', 1,'ESCENCIAL');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (44, 'Impetuoso', 'Petrificado', 'Inmaturo', 'Compulsivo', '', '', 1,'IMPULSIVO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (45, 'Ficticio', 'Tímido', 'Valioso', 'Alfabético', '', '', 1,'OPACADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (46, 'Solemne', 'Falso', 'Irónico', 'Trágico', '', '', 1,'ERRÓNEO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (47, 'Amable', 'Perfecto', 'Adecuado', 'Modesto', '', '', 1,'BENÉVOLO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (48,  'Adusto', 'Mortal', 'Lácteo', 'Abigarrado', '', '', 1,'LETAL');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (49, 'Disgustado', 'Herido', 'Orlado', 'Agobiado', '', '',  1,'LACERADO');
insert preguntas(id_preg,	a1,	a2,	a3,	a4,	a5,	a6,	id_cues,nom_pre) values (50,  'Estudioso', 'Envidioso', 'Altanero', 'Accidental', '', '', 1,'INSOLENTE');


insert into reporte_pma(id,nompdf,bajo,ten_bajo,promedio,ten_alto,alto) values (1,'Comprensión Verbal (V): Capacidad para comprender ideas expresadas en palabras escritas y/o habladas.','','X','','','');
insert into reporte_pma(id,nompdf,bajo,ten_bajo,promedio,ten_alto,alto) values (2,'Concepción Espacial (E): Capacidad para imaginar y concebir objetos en dos o tres dimensiones.','X','','','','');
insert into reporte_pma(id,nompdf,bajo,ten_bajo,promedio,ten_alto,alto) values (3,'Razonamiento (R): Capacidad para resolver problemas lógicos, prever y planear. Manejo de la capacidad deductiva e inductiva.','','','','X','');
insert into reporte_pma(id,nompdf,bajo,ten_bajo,promedio,ten_alto,alto) values (4,'Cálculo Numérico (N): Capacidad de manejar números, de resolver rápidamente y con acierto problemas cuantitativos.','','X','','','');
insert into reporte_pma(id,nompdf,bajo,ten_bajo,promedio,ten_alto,alto) values (5,'Fluidez Verbal (F): Capacidad para hablar y escribir con facilidad y rapidez.','','','','','X');